name: backend-mateo

services:

  database:
    image: postgis/postgis
    ports: 
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/01_init.sql

  mosquitto:
    build:
      context: .
      dockerfile: docker/Dockerfile.mosquitto
      args:
        ARCHIVER_PASSWORD: ${MQTT_ARCHIVER_PASSWORD:-admin_pass}
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  archiver:
    build:
      context: .
      dockerfile: docker/Dockerfile.archiver
    depends_on:
      - database
      - mosquitto
    env_file:
      - .env
    restart: unless-stopped

  toolbox:
    profiles:
      - cli
    build:
      context: .
      dockerfile: docker/Dockerfile.toolbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/project
    working_dir: /project
