FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bulk .

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /bulk /bulk
EXPOSE 8081
ENTRYPOINT ["/bulk"]
